version: "3"
services:
        vlc:
                image: vlc-server
                ports: 
                        - 8080:8080
                        - 8554:8554
                networks:
                        - vlc_net
                volumes:
                        - vlc:/opt/vlc-media/              
networks:
        vlc_net:
volumes:
        vlc:
